### ISSUE TITLE
hash with indifferent access

### ISSUE THREAD

**Issue by nicholalexander** [nicholalexander/basket#59]
when working with json / hash from redis, not having HWIA is annoying.
maybe we just take that ONE method from ActiveSupport?

**Comment by nicholalexander** [comment]
how about we take steve's advice!  🤣 

https://blog.testdouble.com/posts/2019-10-15-lets-hash-this-out/

**Comment by alecclarke** [comment]
sage advice! I say we leave it as-is then 😄

**Comment by nicholalexander** [comment]
ok, sounds good and I'll close this issue for now - we can always revisit.
